# engagement.yaml - 인게이지먼트 파이프라인
# 15분마다 실행되는 통합 인게이지먼트 루프

pipeline:
  id: engagement-loop
  name: "인게이지먼트 루프"
  description: "알림 확인, 맞팔로우, 좋아요, 댓글 등 인게이지먼트 자동화"

  # === 스케줄 ===
  schedule:
    cron: "*/15 * * * *"               # 15분마다
    timezone: "Asia/Seoul"
    enabled: true

  # === 실행 조건 ===
  conditions:
    # 시간 제한 (밤에는 실행 안 함)
    time_range:
      start: "08:00"
      end: "23:00"

    # 시스템 상태 체크
    system_checks:
      - "cpu_usage < 80%"
      - "memory_available > 1GB"

  # === 실행 페이즈 ===
  phases:
    # --- Phase 1: 알림 확인 ---
    - name: "check_notifications"
      description: "모든 채널의 알림 확인"
      parallel: true                   # 채널들 병렬 실행

      tasks:
        - action: "sns/actions/check-notifications"
          channels: ["x", "threads"]
          output: "notifications"

    # --- Phase 2: 멘션 응답 ---
    - name: "respond_to_mentions"
      description: "새 멘션에 답글"
      depends_on: ["check_notifications"]

      condition: "notifications.mentions.count > 0"

      tasks:
        - action: "sns/actions/reply"
          input: "${notifications.mentions}"
          channels: ["x", "threads"]
          use_llm: true
          params:
            max_replies: 10
            tone_ref: "casual"
          output: "replies"

    # --- Phase 3: 맞팔로우 ---
    - name: "follow_back"
      description: "새 팔로워 중 조건 맞는 계정 맞팔"
      depends_on: ["check_notifications"]

      condition: "notifications.new_followers.count > 0"

      tasks:
        - action: "sns/actions/follow-back"
          input: "${notifications.new_followers}"
          channels: ["x", "threads"]
          params:
            filter: "not_bot AND followers > 10"
            max_follows: 10
            delay_minutes: 30
          output: "follow_backs"

    # --- Phase 4: 피드 인게이지먼트 ---
    - name: "engage_feed"
      description: "피드에서 관련 콘텐츠와 상호작용"
      depends_on: ["check_notifications"]

      tasks:
        # 좋아요
        - action: "sns/actions/like"
          channels: ["x", "threads"]
          params:
            target: "feed_relevant"
            topics: "${state.rules.engagement.like_targeting.prefer_topics}"
            limit: 20
          output: "likes"

        # 리포스트
        - action: "sns/actions/repost"
          channels: ["x"]
          params:
            target: "high_quality"
            min_likes: 100
            limit: 3
          output: "reposts"

        # 댓글 (Reply Guy)
        - action: "sns/actions/comment"
          channels: ["x"]
          params:
            target: "big_accounts"
            strategy: "reply_guy"
            use_llm: true
            limit: 5
          output: "comments"

    # --- Phase 5: 결과 기록 ---
    - name: "record_results"
      description: "실행 결과 기록 및 메트릭 업데이트"
      depends_on: ["respond_to_mentions", "follow_back", "engage_feed"]

      tasks:
        - action: "record_activity"
          data:
            replies: "${replies}"
            follow_backs: "${follow_backs}"
            likes: "${likes}"
            reposts: "${reposts}"
            comments: "${comments}"

        - action: "update_metrics"
          metrics:
            - "engagement_today"
            - "replies_today"
            - "likes_today"

  # === 결과 처리 ===
  on_complete:
    # 성공 시 요약
    - condition: "total_actions > 0"
      action: "log"
      message: |
        ✅ 인게이지먼트 루프 완료:
        - 답글: {replies.count}
        - 맞팔로우: {follow_backs.count}
        - 좋아요: {likes.count}
        - 리포스트: {reposts.count}
        - 댓글: {comments.count}

    # 임계값 도달 시 알림
    - condition: "daily_limits_approaching"
      action: "notify"
      channel: "telegram"
      message: "⚠️ 일일 한도 근접: {approaching_limits}"

  on_error:
    - action: "log"
      message: "❌ 인게이지먼트 루프 에러: {error}"

    - action: "notify"
      channel: "telegram"
      message: "❌ 인게이지먼트 에러: {error}"
      severity: "high"

  # === 안전 장치 ===
  safety:
    # 속도 제한
    rate_limits:
      actions_per_minute: 5
      total_actions_per_run: 50

    # 일일 한도 체크
    daily_limits:
      check_before_each_action: true
      stop_on_limit_reached: true

    # 휴먼 패턴
    humanize:
      enabled: true
      random_delays: true
      delay_range_seconds: [5, 30]

  # === 로깅 ===
  logging:
    log_runs: true
    log_path: "data/pipeline_engagement.json"
    include_metrics: true
