# research-to-content.yaml - 리서치 → 콘텐츠 변환 파이프라인
# 리서치 자료를 콘텐츠로 변환하여 큐에 추가

pipeline:
  id: research-to-content
  name: "리서치 → 콘텐츠 변환"
  description: "수집된 리서치를 분석하여 포스팅용 콘텐츠로 변환"

  # === 스케줄 ===
  schedule:
    cron: "0 9 * * *"                  # 매일 오전 9시
    timezone: "Asia/Seoul"
    enabled: true

  # === 트리거 조건 ===
  triggers:
    # 리서치 누적 시 자동 실행
    - condition: "pending_research_count >= ${config.content_style.research_to_content.batch_size}"
      action: "run"

  # === 실행 단계 ===
  steps:
    # --- Step 1: 대기 중인 리서치 가져오기 ---
    - name: "get_pending_research"
      action: "db_query"
      query: |
        SELECT * FROM research
        WHERE status = 'pending'
        AND quality_score >= 0.6
        ORDER BY created_at DESC
        LIMIT ${config.content_style.research_to_content.batch_size}
      output: "research_items"
      on_empty:
        action: "exit"
        message: "변환할 리서치가 없습니다"

    # --- Step 2: 리서치 분석 ---
    - name: "analyze_research"
      action: "llm_analyze"
      prompt: |
        다음 리서치들을 분석해줘.

        **리서치 목록:**
        {research_items}

        **분석 항목:**
        1. 공통 주제/트렌드
        2. 가장 흥미로운 인사이트 3개
        3. 잠재적 콘텐츠 각도 제안

        JSON 형식으로 출력:
        {
          "themes": [...],
          "key_insights": [...],
          "content_angles": [...]
        }
      output: "analysis"

    # --- Step 3: 콘텐츠 생성 ---
    - name: "generate_content"
      action: "llm_generate"
      prompt: |
        다음 분석을 바탕으로 SNS 포스트를 작성해줘.

        **분석 결과:**
        {analysis}

        **콘텐츠 스타일 규칙:**
        {config.content_style}

        **규칙:**
        - 뉴스 나열 X, 관점 있는 글
        - OpenClaw/AI 자동화 FOMO 자극
        - 현대사회 철학적 시각
        - 먼저 쓰는 사람이 가져간다

        **좋은 예시:**
        {config.content_style.good_example}

        **피해야 할 예시:**
        {config.content_style.bad_example}

        **출력 형식 (JSON):**
        {
          "content": "포스트 내용",
          "hook": "첫 문장 (훅)",
          "angle": "콘텐츠 각도",
          "target_channels": ["x", "threads"],
          "suggested_hashtags": [...],
          "fomo_element": "FOMO 요소"
        }
      output: "generated_content"

    # --- Step 4: 콘텐츠 검증 ---
    - name: "validate_content"
      steps:
        # 길이 체크
        - check: "min_length"
          condition: "generated_content.content.length >= ${config.content_style.rules.min_length}"
          on_fail:
            action: "regenerate"
            feedback: "너무 짧습니다. 최소 ${config.content_style.rules.min_length}자 필요"

        # 관점 체크
        - check: "has_perspective"
          condition: "${config.content_style.rules.require_perspective}"
          validator: "llm_check"
          prompt: "이 글에 작성자의 관점/의견이 담겨있는가? (yes/no)"
          on_fail:
            action: "regenerate"
            feedback: "관점이 없습니다. 의견을 추가해주세요"

        # 훅 체크
        - check: "has_hook"
          condition: "${config.content_style.rules.require_hook}"
          validator: "llm_check"
          prompt: "첫 문장이 임팩트 있고 주목을 끄는가? (yes/no)"
          on_fail:
            action: "regenerate"
            feedback: "훅이 약합니다. 더 임팩트 있는 첫 문장 필요"

        # 이모지 체크
        - check: "emoji_count"
          condition: "count_emoji(generated_content.content) <= ${config.content_style.rules.max_emoji}"
          on_fail:
            action: "fix"
            fix_action: "remove_excess_emoji"

    # --- Step 5: 금지어 검증 ---
    - name: "validate_forbidden"
      service: "shared/validator/forbidden"
      input: "${generated_content.content}"
      on_fail:
        action: "regenerate"
        feedback: "금지된 표현 포함: {matched_pattern}"

    # --- Step 6: 유사도 검증 ---
    - name: "validate_similarity"
      service: "shared/validator/similarity"
      input: "${generated_content.content}"
      on_fail:
        action: "regenerate"
        feedback: "기존 포스트와 너무 유사합니다"

    # --- Step 7: 큐에 추가 ---
    - name: "add_to_queue"
      for_each: "channel in generated_content.target_channels"
      action: "db_insert"
      table: "content_queue"
      data:
        raw_content: "${generated_content.content}"
        target_channel: "${channel}"
        hook: "${generated_content.hook}"
        angle: "${generated_content.angle}"
        suggested_hashtags: "${generated_content.suggested_hashtags}"
        source_research_ids: "${research_items.map(r => r.id)}"
        status: "pending"
        priority: 0
        created_at: "now()"

    # --- Step 8: 리서치 상태 업데이트 ---
    - name: "update_research_status"
      action: "db_update"
      table: "research"
      where: "id IN (${research_items.map(r => r.id).join(',')})"
      set:
        status: "processed"
        processed_at: "now()"
        content_queue_id: "${queue_ids}"

  # === 결과 처리 ===
  on_complete:
    - action: "notify"
      channel: "telegram"
      message: |
        ✅ 리서치 → 콘텐츠 변환 완료

        **입력 리서치**: ${research_items.length}개
        **생성된 콘텐츠**: ${generated_count}개
        **대기 큐**: ${queue_total}개

        **훅**: ${generated_content.hook}
        **각도**: ${generated_content.angle}

    - action: "log"
      message: "Generated ${generated_count} content from ${research_items.length} research items"

  on_error:
    - action: "notify"
      channel: "telegram"
      message: "❌ 콘텐츠 생성 실패: ${error}"

  # === 로깅 ===
  logging:
    log_runs: true
    log_path: "data/pipeline_research_to_content.json"
    include_generated_content: true
